### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by sawo** [axet/wget#6]
I am wondering if it will be a big issue to support http proxies when downloading.

**Comment by axet** [comment]
Nice idea.

It would be very easy.

http://stackoverflow.com/questions/1432961/how-do-i-make-httpurlconnection-use-a-proxy

**Comment by sawo** [comment]
You were right, It was not that difficult

**Comment by axet** [comment]
Done with 46af1ac09fb9e267dee9f1b00bf4fce89eb32152

1.2.16

**Comment by sawo** [comment]
Nice solution, but this way every project that relies on VGET (e.g. [WGET](https://github.com/axet/wget)), needs to be modified :(
I think, to activate the proxy via property files/environment variables might be a better solution. There are some name conventions by Oracle: https://docs.oracle.com/javase/7/docs/api/java/net/doc-files/net-properties.html that you could follow. Using property files no need to change any of the applications that depends on VGET.
If you have the possibility, please consider to introduce this amendment.

**Comment by axet** [comment]
@sawo 

I already consider this.

In my opinion libraries should not depend on environment variables or command line arguments, it is space of main application. Even library should not change on system wide parameters like singeltons (static variables) like Authenticator.setDefault(auth).

This library follows this rules. I do not call Authenticator.setDefault(auth) unless proxy authantication fails.

Speaking of compatibility. I should keep two versions API, with deprecated notions. But since this is small library. And I want keep it clean. And new changes it not fixing any bus I decide to break API a little bit. And I decide not to apply new library version 2.0.0+ because I break not too much :)

You can stick to old version of library if you prefer or study and use new one. Emerying fair. For the best!

Thanks for questions, you have good code reading and changing skills. I hope I made my point clear and you find it reasonable. May be you do the same next time as I did!
